### ISSUE TITLE
feat: add login and registration Page

### ISSUE THREAD

**Issue by GrayFlash** [AOSP-NIT-Surat/Bookstore-Frontend-web#1]
## Expected Behavior

- [ ] UI for Sign In
- [ ] UI for Sign Up

**Comment by pavithra-064** [comment]
can you assign me this and you need only the frontend?

**Comment by GrayFlash** [comment]
@pavithra-064 yup, just the frontend for this issue.

**Comment by pavithra-064** [comment]
I have added navbar to the login and registration page .

**Comment by Hetu1107** [comment]
Can I work on sign in and sign up ui?

**Comment by GrayFlash** [comment]
@Hetu1107 there is already a PR for this one. you can comment on the other issue and pick it if you want.

**Comment by Rharsh750** [comment]
can I Work on login and signup page?
