### ISSUE TITLE
feat: create a 404 page

### ISSUE THREAD

**Issue by astonizer** [AOSP-NIT-Surat/Bookstore-Frontend-web#12]
Create a page which should be rendered whenever user tries to access non-existing routes (or the 404 page) in the `/pages` directory.

**Comment by Rharsh750** [comment]
Hello your 404 Page is almost ready 


![image](https://user-images.githubusercontent.com/65497227/136150085-465d73a7-a3ae-4fab-9ce1-c76b5076bb17.png)


please assign me this issues

**Comment by Pranjal7852** [comment]
I have made the 404 page and it is ready to be deployed just I am just unable to get rid of the navbar.
Could you help me figuring out what i am missing?

![Capture](https://user-images.githubusercontent.com/68412756/136152194-1643271d-e7f8-46ba-9663-7e5e570e53c6.JPG)

**Comment by astonizer** [comment]
> I have made the 404 page and it is ready to be deployed just I am just unable to get rid of the navbar. Could you help me figuring out what i am missing?
> 
> ![Capture](https://user-images.githubusercontent.com/68412756/136152194-1643271d-e7f8-46ba-9663-7e5e570e53c6.JPG)

@Pranjal7852 any component you put inside the `<Layout>` component will have the navbar, so you will need to modify the component hierarchy such that the 404 page component doesn't lie within `<Layout>` component.

**Comment by poojavirgo** [comment]
@Pranjal7852 can you please assign this issue?

**Comment by poojavirgo** [comment]
@astonizer can you please assign this issue?

**Comment by astonizer** [comment]
> @astonizer can you please assign this issue?

this issue is already assigned to someone else, but we'll have more coming up

**Comment by Rharsh750** [comment]
@astonizer please check your  pull request 
I am update a 404 page

**Comment by Rharsh750** [comment]
@astonizer  please check your pull request
I am update a 404 page


![image](https://user-images.githubusercontent.com/65497227/136206603-f4083152-e825-4186-b893-3ab8eeff0faa.png)

**Comment by Rharsh750** [comment]
@astonizer Hello please review and merge the request
