### ISSUE TITLE
style: change colors used in register and login pages

### ISSUE THREAD

**Issue by astonizer** [AOSP-NIT-Surat/Bookstore-Frontend-web#13]
Current combination is a blue navbar and brown body color which has to be changed. Use some matching color schemes. Before creating a PR, discuss here some possible good ones.

**Comment by mtahashahid** [comment]
Hi, there below attached are the suggestions from my side for the colors. If you like them then assign this issue to me. Thanks 

![color1](https://user-images.githubusercontent.com/57311675/136152021-47fa6e97-8a33-4c88-9ae1-2c13c5da6276.jpg)
![color2](https://user-images.githubusercontent.com/57311675/136152024-04e440bc-084d-4181-ae16-ea7121b13a3e.jpg)

**Comment by astonizer** [comment]
@mtahashahid LGTM, go ahead and create a PR for the same.
