### ISSUE TITLE
feat: add navigation bar

### ISSUE THREAD

**Issue by astonizer** [AOSP-NIT-Surat/Bookstore-Frontend-web#2]
- [ ] Design and add a basic navbar which should contain the following:
- Logo (Original image or plain text for the time being) which should redirect to home page `/`.
- Navbar links for register `/register` and login `/login`.
<br/>

- [ ] Navbar should be responsive, to support small screens.
- The links should get replaced with a Hamburger button(or any relevant).
- It should display the links in a list, when clicked.

**Comment by SGR007** [comment]
hey, can you assign me this
