### ISSUE TITLE
feat: add UI for Home page.

### ISSUE THREAD

**Issue by GrayFlash** [AOSP-NIT-Surat/Bookstore-Frontend-web#5]
## Expected Behavior

Need to add a homepage, where user can see the books to be bought. Use Dummy data to show layout of cards, needs to be responsive.

**Comment by Hetu1107** [comment]
Can I do this ?

**Comment by 5h15h1r** [comment]
I'll also like to try ,but i wanted to use tailwind CSS

**Comment by GrayFlash** [comment]
@5h15h1r you can try the other issue #6 and feel free to use tailwind or bootstrap, no worries

**Comment by 5h15h1r** [comment]
@GrayFlash  alright, Actually I'll use tailwind CSS but i saw other guys using bootstrap, so what should i do

**Comment by GrayFlash** [comment]
@5h15h1r I think we should stick to one framework actually. You can pick bootstrap, if that's fine??

**Comment by 5h15h1r** [comment]
@GrayFlash  fine , but navigation bar has to be built first so that I can work on the user's page ui

**Comment by GrayFlash** [comment]
@5h15h1r agree with that, ig it is still in pr, although you can add any page till then and later add navigation?? Connecting everything with backend is also gonna show up later. Out backend logic will be used from https://github.com/AOSP-NIT-Surat/Bookstore-ML
