### ISSUE TITLE
feat: create ui for users profile.

### ISSUE THREAD

**Issue by GrayFlash** [AOSP-NIT-Surat/Bookstore-Frontend-web#6]
## Expected Behavior

Create Users profile Page.

**Comment by Mohit2703** [comment]
Can I work on these?

**Comment by 5h15h1r** [comment]
Allow me to make the users Profile page

**Comment by GrayFlash** [comment]
@5h15h1r please comment on an unassigned issue.

**Comment by 5h15h1r** [comment]
@GrayFlash  please specify a specific CSS framework to use , one PR was done with bootstrap and one with just CSS .

**Comment by astonizer** [comment]
@5h15h1r we will mainly use bootstrap
