### ISSUE TITLE
feat: add page to upload photo.

### ISSUE THREAD

**Issue by GrayFlash** [AOSP-NIT-Surat/Bookstore-Frontend-web#7]
## Expected Behavior

Add page to upload photo, and later redirect it and display a form containing photo, and fields like Author, Books Title, and other stuffs.

**Comment by Karthik-SIES-GST** [comment]
@GrayFlash Can you assign this task to me

**Comment by Snehpatel007** [comment]
sir page is just ready 
![Screenshot (236)](https://user-images.githubusercontent.com/81500980/135872663-9dc6a903-06da-4703-ab0a-5179f7199071.png)

can you assign me plz.

**Comment by astonizer** [comment]
@Karthik-SIES-GST yes you can work on this task. Meanwhile @Snehpatel007 you can check out the other repos here and take up any unassigned issue. We will have more tasks coming up for this repo.

**Comment by Snehpatel007** [comment]
why don't you merge my pull request??

**Comment by astonizer** [comment]
@Snehpatel007 i know you have already done the task, but to be fair the tasks are assigned on first come first serve basis. If @Karthik-SIES-GST doesn't respond then we'll merge your pr.
